backend: cloud
backend_config:
  local: {}
  cloud:
    libcloud_provider: GOOGLE_STORAGE
    container_name: "resaas-dev-results"
    driver_kwargs:
      key: TODO
      secret: TODO
      project: resaas-simeon-dev
    storage_key_path: TODO
