apiVersion: v1
kind: Service
metadata:
  labels:
    chainsail.io.service: graphite
  name: graphite
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  # See also: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "2003"
    port: 2003
    targetPort: 2003
  - name: "2004"
    port: 2004
    targetPort: 2004
  - name: "2023"
    port: 2023
    targetPort: 2023
  - name: "2024"
    port: 2024
    targetPort: 2024
  # - name: "8125"
  #   port: 8125
  #   protocol: UDP
  #   targetPort: 8125
  - name: "8126"
    port: 8126
    targetPort: 8126
  selector:
    chainsail.io.service: graphite
