apiVersion: v1
kind: Service
metadata:
  labels:
    chainsail.io.service: postgres
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    chainsail.io.service: postgres
status:
  loadBalancer: {}
