apiVersion: v1
kind: Service
metadata:
  labels:
    chainsail.io.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    chainsail.io.service: redis
status:
  loadBalancer: {}
