apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chainsail.io.service: scheduler-worker
  name: scheduler-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      chainsail.io.service: scheduler-worker
  template:
    metadata:
      labels:
        chainsail.io.service: scheduler-worker
    spec:
      serviceAccountName: chainsail-scheduler
      automountServiceAccountToken: true
      containers:
      - image: chainsail-celery-worker:latest
        imagePullPolicy: IfNotPresent
        name: scheduler-worker
        resources: {}
        env:
          - name: CELERY_BROKER_URL
            value: redis://redis.default.svc.cluster.local:6379/0
          - name: CELERY_RESULT_BACKEND
            value: redis://redis.default.svc.cluster.local:6379/1
          - name: SQLALCHEMY_DATABASE_URI
            value: postgresql://postgres:resaas-dev@postgres.default.svc.cluster.local:5432/postgres
          - name: CHAINSAIL_SCHEDULER_CONFIG
            value: /config/scheduler.yaml
          - name: CONCURRENCY
            value: "5"
        volumeMounts:
          - name: scheduler-config
            readOnly: true
            mountPath: /config/scheduler.yaml
            subPath: scheduler.yaml
          - name: logging-config
            readOnly: true
            mountPath: /config/remote_logging.yaml
            subPath: remote_logging.yaml

      restartPolicy: Always
      volumes:
      - name: scheduler-config
        secret:
          secretName: scheduler-yaml
      - name: logging-config
        secret:
          secretName: remote-logging-yaml