apiVersion: v1
kind: Service
metadata:
  labels:
    chainsail.io.service: scheduler
  name: scheduler
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    chainsail.io.service: scheduler
status:
  loadBalancer: {}
