apiVersion: v1
kind: Service
metadata:
  labels:
    chainsail.io.service: mcmc-stats-server
  name: mcmc-stats-server
spec:
  type: NodePort
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
  selector:
    chainsail.io.service: mcmc-stats-server
