# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  # Pod
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-rc2-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
      restartPolicy: Always # OnFailure should be possible, but not working now (because of Minikube ?)
---
# Service
apiVersion: v1
kind: Service
metadata: 
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
